# Generated by Django 5.2.15 on 2026-06-04 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_name', models.CharField(max_length=200)),
                ('academic_year', models.CharField(max_length=20)),
                ('is_open', models.BooleanField(default=False)),
                ('station_pin', models.CharField(max_length=10)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scope', models.CharField(choices=[('school_wide', 'School Wide'), ('house_specific', 'House Specific')], max_length=20)),
                ('house', models.CharField(blank=True, max_length=50, null=True)),
                ('gender_category', models.CharField(choices=[('Boy', 'Boy'), ('Girl', 'Girl'), ('Open', 'Open')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_number', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('house', models.CharField(max_length=50)),
                ('class_grade', models.CharField(max_length=20)),
                ('has_voted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidate_photos/')),
                ('bio', models.TextField(blank=True, max_length=300, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.position')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.candidate')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.position')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
            options={
                'unique_together': {('voter', 'position')},
            },
        ),
    ]
